configurationset:
  - configuration:
      name: postgresql_config
      uri: postgresql://ep-orange-morning-a8pce62f-pooler.eastus2.azure.neon.tech/neondb?user=neondb_owner&password=npg_7rKdMvzApCJ9
